<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Entry Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .form-container {
            max-width: 400px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .form-group button {
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            color: #fff;
        }
        .submit-btn {
            background-color: #28a745;
        }
        .clear-btn {
            background-color: #dc3545;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form id="data-entry-form">
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="age">Age:</label>
                <input type="number" id="age" name="age" required>
            </div>
            <div class="form-group">
                <label for="email">Mail ID:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <button type="submit" class="submit-btn">Submit</button>
                <button type="button" class="clear-btn" onclick="clearForm()">Clear</button>
            </div>
        </form>
    </div>

    <script>
        document.getElementById('data-entry-form').addEventListener('submit', function(event) {
            event.preventDefault();
            const formData = new FormData(event.target);
            const data = {};
            formData.forEach((value, key) => {
                data[key] = value;
            });

            fetch('https://script.google.com/macros/s/AKfycbxWIGMiMEADaCLjtdl12rz1iSZl13rnbUkHbdO-PQJEiukpLjbbgT7dF6jsqzFtR6Bz/exec', { // Replace with your Google Apps Script web app URL
                method: 'POST',
                contentType: 'application/json',
                body: JSON.stringify(data)
            })
            .then(response => response.text())
            .then(result => {
                alert('Form submitted successfully!');
                clearForm();
            })
            .catch(error => console.error('Error:', error));
        });

        function clearForm() {
            document.getElementById('data-entry-form').reset();
        }
    </script>
</body>
</html>
